apiVersion: v1
kind: ConfigMap
metadata:
  name: sunny-way-config-map
  namespace: default
data:
  application.properties: |
    shardCount={{- .Values.shardCount }}
    queueSize={{- .Values.queueSize }}